# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crashlooper < Formula
  desc "A simple container that crash 💥 after a set amount of time ⏰."
  homepage "https://github.com/pixelfactoryio/crashlooper"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pixelfactoryio/crashlooper/releases/download/v0.1.1/crashlooper_Darwin_arm64.tar.gz"
      sha256 "5ad0bff4556eb3ee020c69990cd59e8c4a44cea84da892ba1c6cdbb512cdae9e"

      def install
        bin.install "crashlooper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/crashlooper/releases/download/v0.1.1/crashlooper_Darwin_x86_64.tar.gz"
      sha256 "5ef2a9f36bb908f1b71e8b2d52ff08b44336d0776ef18c98de40d84b9653d906"

      def install
        bin.install "crashlooper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/crashlooper/releases/download/v0.1.1/crashlooper_Linux_x86_64.tar.gz"
      sha256 "91c0fcb8f184bb14b87bcab96210ae361e662e18b6838154ceab4367645572b7"

      def install
        bin.install "crashlooper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/crashlooper/releases/download/v0.1.1/crashlooper_Linux_armv6.tar.gz"
      sha256 "97809ba8dc2d91417466d236c926e9a15c3cb94b9360966617f2cbd11787116c"

      def install
        bin.install "crashlooper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/crashlooper/releases/download/v0.1.1/crashlooper_Linux_arm64.tar.gz"
      sha256 "8eb877b8423102c2269d582f3ad10c21715a1c04e81b1d9b2cc8ad7a7818cec3"

      def install
        bin.install "crashlooper"
      end
    end
  end
end
