# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Clone git repository in $GIT_GET_PROJECTS_PATH and preserves <githost>/<username>/<repository> structure."
  homepage "https://github.com/pixelfactoryio/git-get"
  version "1.0.2-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pixelfactoryio/git-get/releases/download/v1.0.2-beta/git-get_Darwin_arm64.tar.gz"
      sha256 "5af32dcb4f21550d803b64d277cde9895256c3559525dfb00ea8afd3e7fe0edd"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/git-get/releases/download/v1.0.2-beta/git-get_Darwin_x86_64.tar.gz"
      sha256 "76c7432fe04e9757049269f5ee48bee023b1af8e1af9a226e184cf3cc33ea219"

      def install
        bin.install "git-get"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/git-get/releases/download/v1.0.2-beta/git-get_Linux_arm64.tar.gz"
      sha256 "8c7e9de63215fe7fa2a95c954fb11b8904463a50dc741f4cefc1110e49e93563"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/git-get/releases/download/v1.0.2-beta/git-get_Linux_x86_64.tar.gz"
      sha256 "156decda5696e0961795190436e5f2145deab12c65fcd482fafc543f67396b6c"

      def install
        bin.install "git-get"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/git-get/releases/download/v1.0.2-beta/git-get_Linux_armv6.tar.gz"
      sha256 "dee4e2efd84853948d54b21db683c05283173cd0c52f676d9994c0c06f961207"

      def install
        bin.install "git-get"
      end
    end
  end
end
