# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Needle < Formula
  desc "Small HTTP/1.1, HTTP/2, server with TLS support, that block ads and trackers."
  homepage "https://github.com/pixelfactoryio/needle"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.4/needle_Darwin_x86_64.tar.gz"
      sha256 "cfd537d21cc09551dd6ee4d08ea1f6bf0bd3f55b106ab862ad236c90cf4d0e59"

      def install
        bin.install "needle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.4/needle_Darwin_arm64.tar.gz"
      sha256 "5dcd562f976e0181a0661353d86551329542c37b61d5f676abeda09fdd603284"

      def install
        bin.install "needle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.4/needle_Linux_armv6.tar.gz"
      sha256 "7340b94c628f9fb78e07a548c7f38058880f6efc9304d988ab46c8294c63c399"

      def install
        bin.install "needle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.4/needle_Linux_x86_64.tar.gz"
      sha256 "241be4cbf57c3cd965eba580e107cd5d4d91632e63889fb8f477a3f372976c03"

      def install
        bin.install "needle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.4/needle_Linux_arm64.tar.gz"
      sha256 "7f3c9f8bc583f3c49558308aba03f1ed8d88ca7f9d404bc454e8de51bde41301"

      def install
        bin.install "needle"
      end
    end
  end
end
