# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Needle < Formula
  desc "Small HTTP/1.1, HTTP/2, server with TLS support, that block ads and trackers."
  homepage "https://github.com/pixelfactoryio/needle"
  version "0.2.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.3/needle_Darwin_x86_64.tar.gz"
      sha256 "0355fc5daffc02200a9013e435d5ed3b89a484faf559e08cf8aff789d8468400"
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.3/needle_Darwin_arm64.tar.gz"
      sha256 "3ea740a2cbb5596b802c249c02fc783872f9d470e525997129db6b8da67d67e4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.3/needle_Linux_x86_64.tar.gz"
      sha256 "5065ee96735fe7737db21783dded16384e7db56d2e49a3b32f2cf662c6c4c541"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.3/needle_Linux_armv6.tar.gz"
      sha256 "379a9b98c689d52dac3db91487870968604a7076283581dd2ef47e643551c4b6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelfactoryio/needle/releases/download/v0.2.3/needle_Linux_arm64.tar.gz"
      sha256 "d6ffdf8d98e8cc6ad14151287d52f6df89d7ef8dc3c30d6bfad271f8c510db6f"
    end
  end

  def install
    bin.install "needle"
  end
end
